version: '3'

vars:
  PROJECT_NAME:
    sh: basename $(pwd)

tasks:
  # Setup environment
  setup:
    summary: Setup your local environment with venv
    cmds:
      - pip install virtualenv
      - python -m venv env
      - echo "Activate your environment with => source env/bin/activate"

  pip-install:
    summary: Install pip requirements.
    cmds:
      - pip install --no-cache-dir -r requirements.txt

  pip-req:
    summary: Save current pip requirements.
    cmds:
      - pip freeze | grep -v "@" > requirements.txt

  download-model:
    summary: Download SEALLM model from Huggingface
    cmds:
      - curl -L https://huggingface.co/parinzee/SeaLLM-7B-Chat-GGUF/resolve/main/seallm-7b-chat.q4_k_m.gguf?download=true --output seallm-7b-chat.q4_k_m.gguf

  run:
    summary: Run Streamlit
    cmds:
      - streamlit run main.py
